services:
  neurogym-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neurogym-service
    ports:
      - "8000:8000"
    environment:
      - NEUROGYM_ENV=production
      - LOG_LEVEL=info
    volumes:
      # Mount config directory for custom configurations
      - ./config:/app/config:ro
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Resource limits appropriate for Raspberry Pi 5
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 512M
    networks:
      - neurogym-network

networks:
  neurogym-network:
    driver: bridge
